In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a1.shape

(3,)

In [6]:
a2=np.array([[1,2.0,3.3],[4,5,6.5]])

In [7]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [8]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a2.shape,a3.shape

((2, 3), (2, 3, 3))

In [11]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [12]:
type(a1)

numpy.ndarray

In [13]:
import pandas as pd

In [14]:
df=pd.DataFrame(a2)

In [15]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [16]:
sample_array=np.array([1,2,3])

In [17]:
sample_array

array([1, 2, 3])

In [20]:
ones=np.ones((2,3))

In [21]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
zeros=np.zeros((2,3))

In [25]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
range_array=np.arange(0,10,2)

In [28]:
range_array

array([0, 2, 4, 6, 8])

In [29]:
random_array=np.random.randint(0,10,size=(3,5))

In [30]:
random_array

array([[9, 4, 9, 8, 4],
       [4, 2, 3, 5, 6],
       [4, 6, 4, 7, 7]])

In [31]:
random_array2=np.random.random((5,3))

In [32]:
random_array2

array([[0.56351284, 0.12428427, 0.61654024],
       [0.64478021, 0.26612758, 0.56876177],
       [0.32234398, 0.16244902, 0.5093977 ],
       [0.56767006, 0.09345421, 0.2889082 ],
       [0.79305286, 0.28248084, 0.63461221]])

In [33]:
random_array3=np.random.rand(5,3)

In [34]:
random_array3

array([[0.18861591, 0.99073297, 0.4998349 ],
       [0.73770533, 0.4171628 , 0.72018957],
       [0.32069842, 0.74933729, 0.4441254 ],
       [0.22511803, 0.28804983, 0.31701524],
       [0.16486241, 0.10782537, 0.76385115]])